packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  build:
    '@ryanuo/utils': ^1.2.9

  ci:
    '@antfu/eslint-config': ^2.18.1
    bumpp: ^9.4.1
    eslint: ^9.3.0
    esno: ^4.7.0
    lint-staged: ^15.2.2
    simple-git-hooks: ^2.11.1
    typescript: ^5.4.5
    unbuild: ^2.0.0
    vite: ^5.2.11

  testing:
    vitest: ^1.6.0

  types:
    '@types/node': ^20.12.12

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
